from typing import List

def get_damage_analysis(value_str: str) -> str: ...
def get_transformative_damage(value_str: str) -> str: ...
def gen_character_meta_as_json() -> str: ...
def gen_weapon_meta_as_json() -> str: ...
def gen_artifact_meta_as_json() -> str: ...
def gen_generate_locale_as_json(loc: str) -> str: ...

class CalculatorConfig:
    character: object
    weapon: object
    buffs: List[object] = []
